services:
  web:
    build: ./web
    command: bash -c 
      "
      python script.py -rs
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./web:/web
      - shared_data:/web/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
      - broker
      - ai_service
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery:
    build: ./web
    command: celery -A carDetection worker --loglevel=info
    volumes:
      - ./web:/web
      - shared_data:/shared_data
    environment:
      - DEBUG=1
    depends_on:
      - web
      - broker
      - ai_service

  ai_service:
    build: ./ai
    ports:
      - "8888:80"
    volumes:
      - ./ai:/ai
      - shared_data:/shared_data

volumes:
  db:
  shared_data: